vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.hlsearch = true
vim.opt.mouse = "a"
vim.opt.whichwrap = "b,s,h,l,<,>,[,]"
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.pumheight = 10
vim.opt.showcmd = false
vim.opt.guicursor = vim.opt.guicursor + "a:blinkon0"
vim.opt.encoding = "utf-8"
vim.opt.fileencoding = "utf-8"
vim.opt.fileencodings = "utf-8,iso-2022-jp,cp932,sjis,euc-jp"
vim.opt.undodir = vim.fn.stdpath("data") .. "/undo"
vim.opt.termguicolors = true
vim.opt.foldlevelstart = 99
vim.opt.hidden = true
vim.opt.sessionoptions = "buffers,curdir,tabpages,winsize"
vim.opt.signcolumn = "yes"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt.foldenable = false
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.undofile = true
vim.opt.matchpairs = vim.opt.matchpairs + "「:」,『:』,（:）,【:】,《:》,〈:〉,［:］,‘:’,“:”"
vim.opt.clipboard = "unnamed,unnamedplus"
vim.opt.pumblend = 15
vim.opt.winblend = 15
vim.opt.showmode = false
vim.opt.incsearch = false
vim.opt.updatetime = 100
vim.opt.directory = "/tmp/nvim/swap"
vim.opt.isfname = vim.opt.isfname - "="
vim.opt.iskeyword = vim.opt.iskeyword - "_"
vim.opt.iskeyword = vim.opt.iskeyword + "@"
vim.opt.omnifunc = ""
vim.opt.laststatus = 3
vim.opt.cmdheight = 0
vim.opt.shortmess = vim.opt.shortmess + "Ic"
vim.opt.diffopt = "internal,filler,algorithm:histogram,indent-heuristic"
vim.o.grepprg = "rg --vimgrep --smart-case --follow"
vim.opt.history = 100
vim.o.winborder = "bold"
