# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  globalBuildInputs ? [ ],
}:

{
  ccusage = nodeEnv.buildNodePackage {
    name = "ccusage";
    packageName = "ccusage";
    version = "15.3.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccusage/-/ccusage-15.3.1.tgz";
      sha512 = "Ia4oFTnfSTVxBGel/Dbhtd9hMGmjlW47e0ViyjpSNbQaJE0BLjIBEiw1kxcPe+ydYiPwQkn4vh02us2ECgiedw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Usage analysis tool for Claude Code";
      homepage = "https://github.com/ryoppippi/ccusage#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
