# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anthropic-official-marketplace = {
    pname = "anthropic-official-marketplace";
    version = "9ddfad2e999789e0220cacaf359b64dd873e7d72";
    src = fetchFromGitHub {
      owner = "anthropics";
      repo = "claude-plugins-official";
      rev = "9ddfad2e999789e0220cacaf359b64dd873e7d72";
      fetchSubmodules = false;
      sha256 = "sha256-jlo28awHcmoNN42tmit0Mif9WyrkC2OmjJgRDlLpVCo=";
    };
    date = "2026-07-20";
  };
  ast-grep-marketplace = {
    pname = "ast-grep-marketplace";
    version = "c2a9bc154f4ffe08b25d28d5e852dfac8c0d0d8a";
    src = fetchFromGitHub {
      owner = "ast-grep";
      repo = "agent-skill";
      rev = "c2a9bc154f4ffe08b25d28d5e852dfac8c0d0d8a";
      fetchSubmodules = false;
      sha256 = "sha256-awochSE2OupbsmaGx0xc7wHf0ovVMSdtHv4gZAGWOus=";
    };
    date = "2026-07-03";
  };
  codecompanion-nvim = {
    pname = "codecompanion-nvim";
    version = "v19.20.0";
    src = fetchFromGitHub {
      owner = "olimorris";
      repo = "codecompanion.nvim";
      rev = "v19.20.0";
      fetchSubmodules = false;
      sha256 = "sha256-vDKbjW9izNruCLiPRQEs+yoOrA+YkuyvmdovFTY4nfw=";
    };
  };
  denops-vim = {
    pname = "denops-vim";
    version = "v8.0.2";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "v8.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-lj8yjZrwE9GfNPDIpH4tCI4TTJHkYRlFFCTdqMqWtZg=";
    };
  };
  jdim = {
    pname = "jdim";
    version = "JDim-v0.17.0";
    src = fetchFromGitHub {
      owner = "JDimproved";
      repo = "JDim";
      rev = "JDim-v0.17.0";
      fetchSubmodules = false;
      sha256 = "sha256-8gfEwgpJUaVq/EkHCT3Xf3NasEYn6q7yl86G0onjh+E=";
    };
  };
  neotest = {
    pname = "neotest";
    version = "v5.19.2";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "neotest";
      rev = "v5.19.2";
      fetchSubmodules = false;
      sha256 = "sha256-8qkype0csYvLdcCBpsIiJsulTgvo2QdkHxK7MkV2wAY=";
    };
  };
  neotest-golang = {
    pname = "neotest-golang";
    version = "v2.9.0";
    src = fetchFromGitHub {
      owner = "fredrikaverpil";
      repo = "neotest-golang";
      rev = "v2.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-3nIXy/Lrwph1skT5wn2jKrN10PArBOsOa6V4Nir/f4Y=";
    };
  };
  neotest-plenary = {
    pname = "neotest-plenary";
    version = "3523adcf9ffaad1911960c5813b0136c1b63a2ec";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "neotest-plenary";
      rev = "3523adcf9ffaad1911960c5813b0136c1b63a2ec";
      fetchSubmodules = false;
      sha256 = "sha256-NQGGq1HiBmu/4OhkvNruUWw+OmzS8MQ8LL9dWwaw2oo=";
    };
    date = "2024-09-15";
  };
  nvim-coverage = {
    pname = "nvim-coverage";
    version = "a939e425e363319d952a6c35fb3f38b34041ded2";
    src = fetchFromGitHub {
      owner = "andythigpen";
      repo = "nvim-coverage";
      rev = "a939e425e363319d952a6c35fb3f38b34041ded2";
      fetchSubmodules = false;
      sha256 = "sha256-JQZTXahU3CMXUYZ2Sl09RO7pvvW2X3C/pco62CMfUmw=";
    };
    date = "2024-12-18";
  };
  nvim-dap = {
    pname = "nvim-dap";
    version = "9e848e09a697ee95302a3ef2dd43fd6eb709e570";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "9e848e09a697ee95302a3ef2dd43fd6eb709e570";
      fetchSubmodules = false;
      sha256 = "sha256-IHm3CwO7qUTtOZqhljDjSzz4WbaAJ4kPY384MyZZ9ac=";
    };
    date = "2026-06-19";
  };
  nvim-dap-go = {
    pname = "nvim-dap-go";
    version = "b4421153ead5d726603b02743ea40cf26a51ed5f";
    src = fetchFromGitHub {
      owner = "leoluz";
      repo = "nvim-dap-go";
      rev = "b4421153ead5d726603b02743ea40cf26a51ed5f";
      fetchSubmodules = false;
      sha256 = "sha256-wg9kiW2eAMmg4bvgqaAS9kt7qaVsIWl36BNqRbhZIgo=";
    };
    date = "2025-07-11";
  };
  nvim-dap-ui = {
    pname = "nvim-dap-ui";
    version = "cc9dd33aade7f20bae414d0cba163bc60d4d4b43";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "cc9dd33aade7f20bae414d0cba163bc60d4d4b43";
      fetchSubmodules = false;
      sha256 = "sha256-za3/6W1J6aMvNZQq8ANCq+TGHKHJtSxR/C5t3/oL3DI=";
    };
    date = "2026-07-14";
  };
  nvim-dap-virtual-text = {
    pname = "nvim-dap-virtual-text";
    version = "fbdb48c2ed45f4a8293d0d483f7730d24467ccb6";
    src = fetchFromGitHub {
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "fbdb48c2ed45f4a8293d0d483f7730d24467ccb6";
      fetchSubmodules = false;
      sha256 = "sha256-8hsk+EwnvoHCNhb0dcL9e4hQg9I+t/5Cy9ZoZgcz4fU=";
    };
    date = "2025-05-25";
  };
  nvim-nio = {
    pname = "nvim-nio";
    version = "v1.10.1";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "v1.10.1";
      fetchSubmodules = false;
      sha256 = "sha256-eDbzJAGdUBhTwuD0Nt9FihZj1MmVdQfn/GKIybuu5a8=";
    };
  };
  openai-codex-marketplace = {
    pname = "openai-codex-marketplace";
    version = "db52e28f4d9ded852ab3942cea316258ae4ef346";
    src = fetchFromGitHub {
      owner = "openai";
      repo = "codex-plugin-cc";
      rev = "db52e28f4d9ded852ab3942cea316258ae4ef346";
      fetchSubmodules = false;
      sha256 = "sha256-S/R4kHTcIHBcG0TRX063C7ILXZZm0oMqunchPGg6ToU=";
    };
    date = "2026-07-07";
  };
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "74b06c6c75e4eeb3108ec01852001636d85a932b";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "74b06c6c75e4eeb3108ec01852001636d85a932b";
      fetchSubmodules = false;
      sha256 = "sha256-nkfETDkPiE+Kd2BWYZijgUp9bP8RgFwRmvqJz2BMuq4=";
    };
    date = "2026-04-10";
  };
  popup-nvim = {
    pname = "popup-nvim";
    version = "b7404d35d5d3548a82149238289fa71f7f6de4ac";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "popup.nvim";
      rev = "b7404d35d5d3548a82149238289fa71f7f6de4ac";
      fetchSubmodules = false;
      sha256 = "sha256-dNWz/xovUg55fDZUpVs/2kLphk3lqQyvPtc9ATwbeSQ=";
    };
    date = "2021-11-18";
  };
  statuscol-nvim = {
    pname = "statuscol-nvim";
    version = "887b8a03ea3804628505c9002fd07bd06a3db2e0";
    src = fetchFromGitHub {
      owner = "luukvbaal";
      repo = "statuscol.nvim";
      rev = "887b8a03ea3804628505c9002fd07bd06a3db2e0";
      fetchSubmodules = false;
      sha256 = "sha256-YZ+vXxTREp2OIxBQGt4pYP8hWcswM9XN5BlOSzd6g0Y=";
    };
    date = "2026-07-09";
  };
}
