# This file was generated by nvfetcher, please do not modify it manually.
{ fetchFromGitHub, dockerTools }:
{
  blocc = {
    pname = "blocc";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "shuntaka9576";
      repo = "blocc";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-4OnC9S145i9MtIhKeqh/U1wsjZUps5WNuukpOGes0vA=";
    };
  };
}
