# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.bashcompinit]
inline = "autoload bashcompinit && zsh-defer bashcompinit"

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.ni]
github = "azu/ni.zsh"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"

[plugins.f-sy-h]
github = "z-shell/F-Sy-H"
hooks.post = '''
function set_fast_theme() {
  FAST_HIGHLIGHT_STYLES[path]='fg=cyan,underline'
  FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=cyan,underline' 
  FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=blue'
  FAST_HIGHLIGHT_STYLES[alias]='fg=blue'
  FAST_HIGHLIGHT_STYLES[precommand]='fg=blue'
  FAST_HIGHLIGHT_STYLES[command]='fg=blue'
  FAST_HIGHLIGHT_STYLES[arg0]='fg=025'
  FAST_HIGHLIGHT_STYLES[globbing]='fg=green,bold'
  FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=cyan'
  FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=cyan'
  FAST_HIGHLIGHT_STYLES[default]='fg=cyan'
  FAST_HIGHLIGHT_STYLES[unknown-token]='fg=196'
  FAST_HIGHLIGHT_STYLES[builtin]='fg=blue'
  FAST_HIGHLIGHT_STYLES[global-alias]='fg=green'
}
set_fast_theme
'''

[plugins.tmk]
github = "yuki-yano/tmk"
apply = ["defer"]
hooks.post = '''
bindkey '^[k' tmk
'''

[plugins.tms]
github = "yuki-yano/tms"
apply = ["defer"]
hooks.post = '''
bindkey '^[t' tms
'''

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
hooks.post = '''
if [[ -n "${ZENO_LOADED}" ]]; then
  zle -N zeno-auto-snippet
  zle -N zeno-auto-snippet-and-accept-line
  zle -N zeno-insert-snippet
  zle -N zeno-completion
  zle -N zeno-history-selection
  zle -N zeno-ghq-cd
  bindkey ' '    zeno-auto-snippet
  bindkey '^m'   zeno-auto-snippet-and-accept-line
  bindkey '^x^s' zeno-insert-snippet
  bindkey '^i'   zeno-completion
  bindkey '^r'   zeno-history-selection
  bindkey '^x^f' zeno-ghq-cd
  ZSH_AUTOSUGGEST_CLEAR_WIDGETS+="zeno-auto-snippet-and-accept-line"
fi
'''

[templates]
defer = '''
{{ hooks?.pre | nl }}
{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}
{{ hooks?.post | nl }}
'''
