# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.bashcompinit]
inline = "autoload bashcompinit && zsh-defer bashcompinit"

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.ni]
github = "azu/ni.zsh"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"

[plugins.f-sy-h]
github = "z-shell/F-Sy-H"
hooks.post = '''
zstyle ':fsh:config' work-dir "${XDG_CACHE_HOME:-$HOME/.cache}/f-sy-h"
zstyle ':fsh:config' max-length 1000
zstyle ':fsh:config' theme-manager enabled
zstyle ':fsh:config' bracket-highlighting enabled
zstyle ':fsh:config' path-blocklist '/private/*' '/mnt/slow/**'
zstyle ':fsh:config' chroma-opt-in vim
zstyle ':fsh:config' chroma-cache-seconds 5
zstyle ':fsh:config' chroma-timeout-seconds 2
fsh_theme "${XDG_CONFIG_HOME:-$HOME/.config}/f-sy-h/nightfly.ini"
'''

[plugins.tmk]
github = "yuki-yano/tmk"
apply = ["defer"]
hooks.post = '''
bindkey '^[k' tmk
'''

[plugins.tms]
github = "yuki-yano/tms"
apply = ["defer"]
hooks.post = '''
bindkey '^[t' tms
'''

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
hooks.post = '''
if [[ -n "${ZENO_LOADED}" ]]; then
  bindkey ' '    zeno-auto-snippet
  bindkey '^m'   zeno-auto-snippet-and-accept-line
  bindkey '^x^s' zeno-insert-snippet
  bindkey '^i'   zeno-completion
  bindkey '^r'   zeno-history-selection
  bindkey '^x^f' zeno-ghq-cd
  ZSH_AUTOSUGGEST_CLEAR_WIDGETS+="zeno-auto-snippet-and-accept-line"
fi
'''

[templates]
defer = '''
{{ hooks?.pre | nl }}
{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}
{{ hooks?.post | nl }}
'''
