-- lua_add {{{
local dap = require("dap")
local dapui = require("dapui")
dapui.setup()
dap.listeners.after.event_initialized["dapui_config"] = function()
    dapui.open({})
end
dap.listeners.before.event_terminated["dapui_config"] = function()
    dapui.close({})
end
dap.listeners.before.event_exited["dapui_config"] = function()
    dapui.close({})
end
vim.keymap.set("n", "<leader>du", function()
    dapui.toggle({})
end, { desc = "[d]ap [u]i" })
vim.keymap.set("n", "<leader>de", function()
    require("dapui").eval()
end, { desc = "[d]ap [e]val" })
vim.keymap.set("n", "<leader>db", function()
    require("dap").toggle_breakpoint()
end, { desc = "toggle [d]ebug [b]reakpoint" })
vim.keymap.set("n", "<leader>dB", function()
    require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "[d]ebug [B]reakpoint" })
vim.keymap.set("n", "<leader>dc", function()
    require("dap").continue()
end, { desc = "[d]ebug [c]ontinue (start here)" })
vim.keymap.set("n", "<leader>dC", function()
    require("dap").run_to_cursor()
end, { desc = "[d]ebug [C]ursor" })
vim.keymap.set("n", "<leader>dg", function()
    require("dap").goto_()
end, { desc = "[d]ebug [g]o to line" })
vim.keymap.set("n", "<leader>do", function()
    require("dap").step_over()
end, { desc = "[d]ebug step [o]ver" })
vim.keymap.set("n", "<leader>dO", function()
    require("dap").step_out()
end, { desc = "[d]ebug step [O]ut" })
vim.keymap.set("n", "<leader>di", function()
    require("dap").step_into()
end, { desc = "[d]ebug [i]nto" })
vim.keymap.set("n", "<leader>dj", function()
    require("dap").down()
end, { desc = "[d]ebug [j]ump down" })
vim.keymap.set("n", "<leader>dk", function()
    require("dap").up()
end, { desc = "[d]ebug [k]ump up" })
vim.keymap.set("n", "<leader>dl", function()
    require("dap").run_last()
end, { desc = "[d]ebug [l]ast" })
vim.keymap.set("n", "<leader>dp", function()
    require("dap").pause()
end, { desc = "[d]ebug [p]ause" })
vim.keymap.set("n", "<leader>dr", function()
    require("dap").repl.toggle()
end, { desc = "[d]ebug [r]epl" })
vim.keymap.set("n", "<leader>dR", function()
    require("dap").clear_breakpoints()
end, { desc = "[d]ebug [R]emove breakpoints" })
vim.keymap.set("n", "<leader>ds", function()
    require("dap").session()
end, { desc = "[d]ebug [s]ession" })
vim.keymap.set("n", "<leader>dt", function()
    require("dap").terminate()
end, { desc = "[d]ebug [t]erminate" })
vim.keymap.set("n", "<leader>dw", function()
    require("dap.ui.widgets").hover()
end, { desc = "[d]ebug [w]idgets" })
--}}}
